version: "3"

services:
  master:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: ["uvicorn", "code.master:app", "--host", "0.0.0.0", "--port", "8000"]

  secondary1:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    command: [ "uvicorn", "code.secondary:app", "--host", "0.0.0.0", "--port", "8001"]

  secondary2:
    build: .
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    command: [ "uvicorn", "code.secondary:app", "--host", "0.0.0.0", "--port", "8002" ]